# Generated by Django 6.0.5 on 2026-05-21 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula/Cédula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('carreras_id_carrera', models.ForeignKey(db_column='carreras_id_carrera', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultades_id_facultad',
            field=models.ForeignKey(db_column='facultades_id_facultad', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.facultad', verbose_name='Facultad'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('año_publicacion', models.IntegerField(verbose_name='Año de Publicación')),
                ('cantidad_total', models.IntegerField(verbose_name='Cantidad Total')),
                ('cantidad_disponible', models.IntegerField(verbose_name='Cantidad Disponible')),
                ('ubicacion_fisica', models.CharField(max_length=100, verbose_name='Ubicación Física')),
                ('autores_id_autor', models.ForeignKey(db_column='autores_id_autor', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor', verbose_name='Autor')),
                ('categorias_id_categoria', models.ForeignKey(db_column='categorias_id_categoria', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoria', verbose_name='Categoría')),
                ('editoriales_id_editorial', models.ForeignKey(db_column='editoriales_id_editorial', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.editorial', verbose_name='Editorial')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='MaterialCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carreras_id_carrera', models.ForeignKey(db_column='carreras_id_carrera', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.carrera')),
                ('materiales_id_material', models.ForeignKey(db_column='materiales_id_material', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.material')),
            ],
            options={
                'verbose_name': 'Material - Carrera',
                'verbose_name_plural': 'Materiales - Carreras',
                'db_table': 'materiales_y_carreras',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='carreras',
            field=models.ManyToManyField(through='biblioteca.MaterialCarrera', to='biblioteca.carrera', verbose_name='Carreras Asociadas'),
        ),
        migrations.CreateModel(
            name='MaterialGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generos_id_genero', models.ForeignKey(db_column='generos_id_genero', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.genero')),
                ('materiales_id_material', models.ForeignKey(db_column='materiales_id_material', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.material')),
            ],
            options={
                'verbose_name': 'Material - Género',
                'verbose_name_plural': 'Materiales - Géneros',
                'db_table': 'materiales_y_generos',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='generos',
            field=models.ManyToManyField(through='biblioteca.MaterialGenero', to='biblioteca.genero', verbose_name='Géneros'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(auto_now_add=True, verbose_name='Fecha de Préstamo')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('ALUMNOS_id_alumno', models.ForeignKey(db_column='ALUMNOS_id_alumno', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.alumno', verbose_name='Alumno')),
                ('MATERIALES_id_material', models.ForeignKey(db_column='MATERIALES_id_material', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.material', verbose_name='Material')),
                ('administrador_usuariosbibliosoft_id', models.ForeignKey(db_column='administrador_usuariosbibliosoft_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que presta')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_devolucion', models.DateField(auto_now_add=True, verbose_name='Fecha de Devolución')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('multa', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Multa')),
                ('prestamos_id_prestamo', models.OneToOneField(db_column='prestamos_id_prestamo', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='tipodocumento_id_tipo',
            field=models.ForeignKey(db_column='tipodocumento_id_tipo', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.tipodocumento', verbose_name='Tipo de Documento'),
        ),
    ]
