# Generated by Django 6.0.5 on 2026-05-21 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='material',
            name='edicion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Edición'),
        ),
        migrations.AddField(
            model_name='material',
            name='estado_material',
            field=models.CharField(default='DISPONIBLE', max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='material',
            name='issn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISSN'),
        ),
        migrations.AddField(
            model_name='material',
            name='numeracion_dewey',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numeración Dewey'),
        ),
        migrations.AddField(
            model_name='material',
            name='numero_entrada',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Entrada'),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Material'),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo_registro',
            field=models.CharField(choices=[('LIBRO', 'Libro'), ('TRABAJO_INVESTIGACION', 'Trabajo de Investigación'), ('OTROS', 'Otros Materiales')], default='LIBRO', max_length=50, verbose_name='Tipo de Registro'),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Trabajo'),
        ),
        migrations.AddField(
            model_name='material',
            name='titulo_grado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título de Grado'),
        ),
        migrations.AlterField(
            model_name='material',
            name='autores_id_autor',
            field=models.ForeignKey(blank=True, db_column='autores_id_autor', null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='material',
            name='año_publicacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de Publicación'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cantidad_disponible',
            field=models.IntegerField(default=1, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cantidad_total',
            field=models.IntegerField(default=1, verbose_name='Cantidad Total'),
        ),
        migrations.AlterField(
            model_name='material',
            name='categorias_id_categoria',
            field=models.ForeignKey(blank=True, db_column='categorias_id_categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='material',
            name='editoriales_id_editorial',
            field=models.ForeignKey(blank=True, db_column='editoriales_id_editorial', null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.editorial', verbose_name='Editorial'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipodocumento_id_tipo',
            field=models.ForeignKey(blank=True, db_column='tipodocumento_id_tipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.tipodocumento', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='material',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación Física'),
        ),
    ]
