# Generated by Django 6.0.5 on 2026-05-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_material_descripcion_material_edicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='celular',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de celular'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ciudad_origen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de Origen'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='direccion_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Actual (Barrio y nombre de Calle)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Paraguaya', max_length=50, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nacionalidad_otros',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad (Otros)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='otros_numeros',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otros números'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CI', 'CI'), ('DNI', 'DNI')], default='CI', max_length=10, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
