# Generated by Django 6.0.5 on 2026-05-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alumno_celular_alumno_ciudad_alumno_ciudad_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='carnet_activo',
            field=models.BooleanField(default=False, verbose_name='Carnet Activo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='carnet_fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega del Carnet'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='lector_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lector N°'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='numero_matricula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Matrícula'),
        ),
    ]
