# Generated by Django 6.0.5 on 2026-05-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alumno_carnet_activo_alumno_carnet_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='estado_material',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], default='BUENO', max_length=50, verbose_name='Estado del Material'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='pago_multa',
            field=models.BooleanField(default=False, verbose_name='¿Pagó la Multa?'),
        ),
    ]
