# Generated by Django 6.0.5 on 2026-05-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_devolucion_estado_material_devolucion_pago_multa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='autores_id_autor',
        ),
        migrations.AddField(
            model_name='material',
            name='autores_id_autor',
            field=models.ManyToManyField(blank=True, to='biblioteca.autor', verbose_name='Autor/es'),
        ),
    ]
