# Generated by Django 6.0.5 on 2026-05-22 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_remove_material_autores_id_autor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carreras_id_carrera',
            field=models.ForeignKey(db_column='carreras_id_carrera', on_delete=django.db.models.deletion.PROTECT, to='biblioteca.carrera', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='facultades_id_facultad',
            field=models.ForeignKey(db_column='facultades_id_facultad', on_delete=django.db.models.deletion.PROTECT, to='biblioteca.facultad', verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='prestamos_id_prestamo',
            field=models.OneToOneField(db_column='prestamos_id_prestamo', on_delete=django.db.models.deletion.PROTECT, to='biblioteca.prestamo', verbose_name='Préstamo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='categorias_id_categoria',
            field=models.ForeignKey(blank=True, db_column='categorias_id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='material',
            name='editoriales_id_editorial',
            field=models.ForeignKey(blank=True, db_column='editoriales_id_editorial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.editorial', verbose_name='Editorial'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipodocumento_id_tipo',
            field=models.ForeignKey(blank=True, db_column='tipodocumento_id_tipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.tipodocumento', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='ALUMNOS_id_alumno',
            field=models.ForeignKey(db_column='ALUMNOS_id_alumno', on_delete=django.db.models.deletion.PROTECT, to='biblioteca.alumno', verbose_name='Alumno'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='MATERIALES_id_material',
            field=models.ForeignKey(db_column='MATERIALES_id_material', on_delete=django.db.models.deletion.PROTECT, to='biblioteca.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='administrador_usuariosbibliosoft_id',
            field=models.ForeignKey(db_column='administrador_usuariosbibliosoft_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que presta'),
        ),
    ]
