# Generated by Django 6.0.5 on 2026-05-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_alter_alumno_carreras_id_carrera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='numero_paginas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Páginas'),
        ),
    ]
