# Generated by Django 6.0.5 on 2026-05-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_material_numero_paginas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_recargo', models.DecimalField(decimal_places=0, default=1500, max_digits=8, verbose_name='Monto del recargo por día')),
                ('recargo_activo', models.BooleanField(default=True, verbose_name='¿Recargo activo?')),
                ('horario_lunes_viernes', models.CharField(default='07:00 a 21:00 hs.', max_length=100, verbose_name='Horario de atención Lunes a Viernes')),
                ('abren_sabados', models.BooleanField(default=True, verbose_name='¿Abren los Sábados?')),
                ('horario_sabados', models.CharField(default='08:00 a 12:00 hs.', max_length=100, verbose_name='Horario de atención Sábados')),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuraciones Generales',
            },
        ),
    ]
