# Generated by Django 6.0.5 on 2026-05-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_configuraciongeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad prestada'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='numero_entrada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de entrada'),
        ),
    ]
