# Generated by Django 6.0.5 on 2026-05-29 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_prestamo_cantidad_prestamo_numero_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='prorrogado',
            field=models.BooleanField(default=False, verbose_name='Prorrogado'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Préstamo'),
        ),
    ]
