# Generated by Django 6.0.5 on 2026-05-31 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_prestamo_prorrogado_alter_prestamo_fecha_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='ubicacion_fisica',
        ),
    ]
