# Generated by Django 6.0.5 on 2026-06-01 00:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_remove_material_ubicacion_fisica'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaMaterial',
            fields=[
                ('id_baja', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad dada de baja')),
                ('numero_entrada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Entrada')),
                ('motivo', models.CharField(choices=[('MOJADO', 'Se mojó'), ('ROTO', 'Se rompió'), ('NO_ENTREGADO', 'Nunca se entregó'), ('PERDIDO', 'Pérdida'), ('OTRO', 'Otro')], max_length=50, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_baja', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Baja')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Baja de Material',
                'verbose_name_plural': 'Bajas de Materiales',
            },
        ),
    ]
