# Generated by Django 6.0.5 on 2026-06-01 00:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_bajamaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajamaterial',
            name='fecha_baja',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Baja'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Préstamo'),
        ),
    ]
