# Generated by Django 6.0.5 on 2026-06-01 21:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_alter_bajamaterial_fecha_baja_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('ELIMINACION', 'Eliminación'), ('INICIO_SESION', 'Inicio de Sesión'), ('CERRAR_SESION', 'Cierre de Sesión'), ('PRORROGA', 'Prórroga'), ('ACTIVACION_CARNET', 'Activación de Carnet'), ('DESACTIVACION_CARNET', 'Desactivación de Carnet')], max_length=50, verbose_name='Acción')),
                ('tabla', models.CharField(max_length=100, verbose_name='Módulo/Tabla')),
                ('registro_id', models.CharField(blank=True, max_length=50, verbose_name='ID Registro')),
                ('detalle', models.TextField(verbose_name='Detalle de la Acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
