# Generated by Django 6.0.5 on 2026-06-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0015_registroauditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado_material',
            field=models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], default='BUENO', max_length=50, null=True, verbose_name='Estado del Material'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='multa',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Multa'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='observaciones_devolucion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de Devolución'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='pago_multa',
            field=models.BooleanField(default=False, verbose_name='¿Pagó la Multa?'),
        ),
        migrations.AlterField(
            model_name='material',
            name='titulo',
            field=models.CharField(max_length=400, verbose_name='Título'),
        ),
        migrations.DeleteModel(
            name='Devolucion',
        ),
    ]
